project:
  type: book

book:
  title: "SISTEMA DE INVENTARIO"
  author: "Jazmin Sarahí Flores Gómez"
  date: "27/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - formulacion.qmd
    - summary.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt

editor: visual

