project:
  type: book

book:
  title: "SISTEMA DE INVENTARIO"
  author: "Jazmin Sarahí Flores Gómez"
  date: "27/9/2024"
  chapters:
    - index.qmd
    - introduccion.qmd
    - formulacion.qmd
    - dinamica.qmd
    - Costo.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: [journal, theme-dark.scss]
  pdf:
    documentclass: scrreprt
editor: visual

