# Dinámica del Modelo

La dinámica del sistema evoluciona en el tiempo, de modo que en cada etapa de desición $t\in \{ 0,1,2, \dotso,N \}$ el nivel de inventario es $x_t=x \in \mathbf{X}$ y el controlador toma una desición admisible $a_t= a \in A(x)$, es decir, solicita cierta cantidad de articulos de acuerdo a la cantidad existente. Entonces: se produce un costo $\mathbf{C}(x,a)$; luego, el sistema evoluciona a un nuevo estado $x_{t+1}=y \in \mathbf{X}$ de acuerdo a la ley de transición $\mathbf{P}_{x,y}(a)$, la cual explicaremos a detalle en esta sección.

Consideremos $\{ \xi_t\}$ una sucesión de variables aleatorias independientes e idénticamente distribuidas, definidas en el mismo espacio de probabilidad $(\Omega,\mathbf{F},P)$; tal que toman valores en algun conjunto numerable $\mathbf{S}$ y función de probabilidad comun $f$ conocida. Es decir, para cada $k\in\mathbf{S}$ $$
f(k)=P[\xi_t=k]
$$ entonces el nivel de inventario es representado en cada periodo por medio de la siguiente ecuación: $$x_{t+1}=(x_t+a_t-\xi_t)^{+}=\max(x_t+a_t-\xi_t,0)$$

Dicha expresión puede ser interpretada del siguiente modo: la cantidad de producto en el periodo $t+1$, será la cantidad $x_t$ que existía hasta el periodo anterior, más la cantidad $a_t$ solicitada de producto, menos la demanda $\xi_t$ que se surte a los clientes. Dado que no hay acumulación de demanda, la cantidad de producto no puede ser negativa, de manera que, si no se logra surtir toda la demanda, el nivel de inventario en el siguiente periodo será cero.

Suponemos que el nivel de inventario se a venido monitoreando hata el periodo $t$. Entonces, la probabilidad de contar con una cantidad $x$ de articulos, solicitar $a$ articulos y transitar a un nivel de inventario $y$ es: $$
\mathbf{P}_{x,y}(a)= P[x_{t+1}=y \mid x_t=x, a_t=a]
$$ $$
=P[(x_t+a_t-\xi_t)^{+}=y \mid x_t=x, a_t=a]
$$ $$
=P[(x+a-\xi_t)^{+}=y]
$$ $$
=\sum_{k\in Y}f(k)
$$ donde $Y=\{k \in \mathbf{S} \mid (x+a-k)^+=y\}$

# Ejemplo:

Consideremos el problema de control de inventario donde la capacidad del almacen es $M=2$, entonces $$
\mathbf{X}=\mathbf{A}=\{0,1,2\}
$$ por lo que, existen tres posibilidades: el almacen está vacio, contiene 1 árticulo, o contiene 2 árticulos. Además supongamos que la demanda $\xi_t$ toma valores en el conjunto $\mathbf{S}=\{0,1,2,3\}$ con distribución de probabilidad unifore en todos los periodos, es decir $P[\xi_t=k]=\frac{1}{4}$, para cada $k\in\mathbf{S}$.

Para la acción $a=0$ la cual es admisible para todos los estados, tenemos la siguiente tabla de transiciones:

| x                        | a                       | y                      | $\mathbf{P}_{x,y}(a)$ |
|--------------------------|-------------------------|------------------------|-----------------------|
| contar con $0$ artículos | solicitar $0$ artículos | contar con 0 artículos | 1                     |
| contar con $0$ artículos | solicitar $0$ artículos | contar con 1 artículos | 0                     |
| contar con $0$ artículos | solicitar $0$ artículos | contar con 2 artículos | 0                     |
| contar con $1$ artículo  | solicitar $0$ artículos | contar con 0 artículos | $\frac{3}{4}$         |
| contar con $1$ artículo  | solicitar $0$ artículos | contar con 1 artículos | $\frac{1}{4}$         |
| contar con $1$ artículo  | solicitar $0$ artículos | contar con 2 artículos | 0                     |
| contar con $2$ artículos | solicitar $0$ artículos | contar con 0 artículos | $\frac{2}{4}$         |
| contar con $2$ artículos | solicitar $0$ artículos | contar con 1 artículos | $\frac{1}{4}$         |
| contar con $2$ artículos | solicitar $0$ artículos | contar con 2 artículos | $\frac{1}{4}$         |

```{dot}
digraph MDP {
node[color=pink]
edge[arrowsize=0.3,color=pink]
  0 -> 0 [label="1",fontsize="8"];
  2 -> 0 [label="0.5",fontsize="8"]
  1 -> 0 [label="0.75",fontsize="8"]
  1 -> 1 [label="0.25",fontsize="8"]
  2 -> 1 [label="0.25",fontsize="8"]
  2 -> 2 [label="0.25",fontsize="8"]
}
```

Para la acción $a=1$ la cual es admisible cuando el nivel del almacen es $0$ o $1$, tenemos la siguiente tabla de transiciones:

| x                        | a                      | y                      | $\mathbf{P}_{x,y}(a)$ |
|-------------------|------------------|------------------|------------------|
| contar con $0$ artículos | solicitar $1$ artículo | contar con 0 artículos | $\frac{3}{4}$         |
| contar con $0$ artículos | solicitar $1$ artículo | contar con 1 artículos | $\frac{1}{4}$         |
| contar con $0$ artículos | solicitar $1$ artículo | contar con 2 artículos | 0                     |
| contar con $1$ artículo  | solicitar $1$ artículo | contar con 0 artículos | $\frac{2}{4}$         |
| contar con $1$ artículo  | solicitar $1$ artículo | contar con 1 artículos | $\frac{1}{4}$         |
| contar con $1$ artículo  | solicitar $1$ artículo | contar con 2 artículos | $\frac{1}{4}$         |

```{dot}
digraph MDP {
node[color=pink]
edge[arrowsize=0.3,color=pink]
  0 -> 0 [label="0.75",fontsize="8"];
  0 -> 1 [label="0.25",fontsize="8"];
  1 -> 0 [label="0.5",fontsize="8"]
  1 -> 1 [label="0.25",fontsize="8"]
  1 -> 2 [label="0.25",fontsize="8"]
 
}
```
Para la acción $a=2$ la cual es admisible únicamente cuando el nivel del almacen es $0$ tenemos la siguiente tabla de transiciones:


| x                        | a                       | y                      | $\mathbf{P}_{x,y}(a)$ |
|--------------------------|-------------------------|------------------------|-----------------------|
| contar con $0$ artículos | solicitar $2$ artículos | contar con 0 artículos | $\frac{2}{4}$         |
| contar con $0$ artículos | solicitar $2$ artículos | contar con 1 artículos | $\frac{1}{4}$         |
| contar con $0$ artículos | solicitar $2$ artículos | contar con 2 artículos | $\frac{1}{4}$         |

```{dot}
digraph MDP {
node[color=pink]
edge[arrowsize=0.3,color=pink]
  0 -> 0 [label="0.5",fontsize="8"];
  0 -> 1 [label="0.25",fontsize="8"];
  0 -> 2 [label="0.25",fontsize="8"]
  
 
}
```